"""Generate on-device assets for the ESP32 sketch:
  - firmware/esp32_llm/vocab.h : token id -> raw UTF-8 bytes, so the device just
    Serial.write()s the bytes of each generated token (llama2.c style).
  - prints token IDs for a sample prompt as a pipeline sanity check.
"""

import argparse
import os

from tokenizers import Tokenizer

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "firmware", "esp32_llm", "vocab.h")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--vocab", type=int, default=16384)
    parser.add_argument("--prompt", default="Once upon a time")
    args = parser.parse_args()

    tokenizer_path = os.path.join(
        HERE, "..", "data", f"bpe{args.vocab}.json"
    )
    tok = Tokenizer.from_file(tokenizer_path)
    V = tok.get_vocab_size()

    # Raw bytes per token: decode single-id sequences. For the ASCII TinyStories
    # domain this reconstructs text exactly when pieces are concatenated.
    blob = bytearray()
    offs = [0]
    for i in range(V):
        s = tok.decode([i])
        blob.extend(s.encode("utf-8"))
        offs.append(len(blob))

    with open(OUT, "w") as f:
        f.write("// Generated by src/gen_assets.py -- token id -> raw UTF-8 bytes.\n")
        f.write("#ifndef VOCAB_H\n#define VOCAB_H\n")
        f.write(f"#define VOCAB_N {V}\n")
        f.write(f"static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 20):
            f.write("  " + ",".join(str(b) for b in blob[i:i+20]) + ",\n")
        f.write("};\n")
        f.write(f"static const int VOCAB_OFF[{len(offs)}] = {{\n")
        for i in range(0, len(offs), 20):
            f.write("  " + ",".join(str(o) for o in offs[i:i+20]) + ",\n")
        f.write("};\n#endif\n")

    print(f"wrote {OUT}: {V} tokens, blob {len(blob)/1024:.0f} KB")

    ids = tok.encode(args.prompt).ids
    print(f'prompt "{args.prompt}" -> {len(ids)} ids: {ids}')
    print(f"round-trip: {tok.decode(ids)!r}")


if __name__ == "__main__":
    main()
